### PR TITLE
Improved Logging. (Muting and "source" definition)

### PR DESCRIPTION
**Pull request by LunaTheFoxgirl**
Adds the ability to mute output from sources in variying levels, or mute the "off" level, which mutes everything from a source.

### CODE REVIEW

**Comment by LunaTheFoxgirl** [comment]
See the sample i created for an example of usage.

**Comment by Quentin01** [comment]
I'm sorry, but I think there was a misunderstanding on #47 and you didn't quite understand what I was expecting. Indeed, I was waiting for the function `Logger::setSourceLevel` to work as the function `Handler::setLevel`. It works by muting all the levels that are *higher* than the one passed in parameter, kinda like a "verbose" parameter. 

For example, if you provide `Lever::Error`, we will only display `Level::Error`, `Level::Fatal` and `Level::Assert`. See the implementation of [`Handler::shouldLog`](https://github.com/Lugdunum3D/Lugdunum/blob/e087df133c8576b37db5140e88f22decbf4167d6/src/lug/System/Logger/Handler.cpp#L34). 

I'm not fully available right now; I will do a review of the C++ and the guidelines as soon as possible.

**Comment by LunaTheFoxgirl** [comment]
Fair enough, could i maybe do like a logging mode select, then. I like this more finegrained control, like if you want info, no warnings, but also errors, it's possible with this.
Though i can change it, if needed ^^;

**Comment by saveman71** [comment]
Thank you for your understanding ;) We'll discuss this internally a lil bit before coming back to you.

In the meantime, I suggest you read [this very good article](https://www.notion.so/Keeping-Commit-Histories-Clean-0f717c4e802c4a0ebd852cf9337ce5d2) which goes over how to write good commit messages, best practices for git and especially rebasing (or rewriting) the history. As we'd like to keep a good history with descriptive commit messages (i.e. not "more stuff" ^^), we would love that you apply those principles when you're working with us!

However, I don't think it's worth it that you rewrite the history of your changes right now since you're probably going to have to change a lot of things, but it's a good read anyway!

**Comment by LunaTheFoxgirl** [comment]
Yeah, my knowledge of git is pretty basic, i'll definately give it a read. c:

**Comment by LunaTheFoxgirl** [comment]
I'm implementing both ways via a macro right now, then you can see which fits the best. c:

**Comment by LunaTheFoxgirl** [comment]
Whenever you find the one you want the most, tell which, and i'll get rid of the other one :P
I realise that i've made a mistake on the header, first caught it now. One of the downsides of doing fast iteration x.x

**Comment by Quentin01** [comment]
I have discussed with @saveman71 and we agreed to have a more fine-grained control over the level of logging. However, we also want it to be handled in the `Handler` and not directly in the `Logger`, because a user might want to use different logging levels for each source depending of the output `Handler`.

Instead of using a `std::vector<Level>`, I think it's best to use bit flags (if you need clarification about that and how to implement it in the engine, you can ask us).
And because of these changes, we also need to apply this logic to the method `Handler::setLevel` and rename it `Handler::setLevels`.

For example:
```cpp
handler.setLevels(Level::Warning | Level::Error | Level::Fatal | Level::Assert);
handler.setSourceLevels("foo", Level::Info | Level::Error);
```

Of course, by default we log everything for every sources.

**Comment by LunaTheFoxgirl** [comment]
Ok, looking at it now. c:

**Comment by LunaTheFoxgirl** [comment]
About bitflags, i don't see that the `LUG_LOG_LEVELS` specify any values to the flags, will normal bit flag code still work with that? @Quentin01

**Comment by Quentin01** [comment]
To implement bit flags, you need to update that part of the code to assign a value to each element in the `enum`. (And you can also remove the element `Level::Off`)

**Comment by LunaTheFoxgirl** [comment]
Okies, i will do that as soon as I have time c:

**Comment by LunaTheFoxgirl** [comment]
~~So they way you've made the flags work currently, confuses me alot. Can't i just turn it into an enum. Or would that break something else?~~ Nevermind, figured it out.

```cpp
#define LUG_LOG_LEVELS(PROCESS, VALUES)     \
    PROCESS(Debug, 0x01)                    \
    PROCESS(Info, 0x02)                     \
    PROCESS(Warning, 0x04)                  \
    PROCESS(Error, 0x08)                    \
    PROCESS(Fatal, 0x10)                    \
    PROCESS(Assert, 0x20)                   \



namespace lug {
namespace System {
namespace Logger {

#define LUG_LOG_ENUM(CHANNEL, VALUES) CHANNEL,
enum class Level : uint8_t {
    LUG_LOG_LEVELS(LUG_LOG_ENUM, VALUES)
};
#undef LUG_LOG_ENUM
```

Am i entirely wrong? xD
```cpp
#define LUG_LOG_LEVELS(PROCESS)     \
    PROCESS(Debug=0x01)                    \
    PROCESS(Info=0x02)                     \
    PROCESS(Warning=0x04)                  \
    PROCESS(Error=0x08)                    \
    PROCESS(Fatal=0x10)                    \
    PROCESS(Assert=0x20)                   \



namespace lug {
namespace System {
namespace Logger {

#define LUG_LOG_ENUM(CHANNEL) CHANNEL,
enum class Level : uint8_t {
    LUG_LOG_LEVELS(LUG_LOG_ENUM)
};
#undef LUG_LOG_ENUM
```

This compiles too. I'm not exactly sure how to do this part. x.x

**Comment by Quentin01** [comment]
This technique is called [X Macro](https://en.wikipedia.org/wiki/X_Macro) and is really useful when you want to use a list of items at different places in the code.

The good way of doing it is like that:
```cpp
#define LUG_LOG_LEVELS(PROCESS) \
    PROCESS(Debug, 0x01)        \
    PROCESS(Info, 0x02)         \
    PROCESS(Warning, 0x04)      \
    PROCESS(Error, 0x08)        \
    PROCESS(Fatal, 0x10)        \
    PROCESS(Assert, 0x20)

namespace lug {
namespace System {
namespace Logger {

#define LUG_LOG_ENUM(CHANNEL, VALUE) CHANNEL = VALUE,
enum class Level : uint8_t {
    LUG_LOG_LEVELS(LUG_LOG_ENUM)
};
#undef LUG_LOG_ENUM

LUG_SYSTEM_API std::ostream& operator<<(std::ostream& os, Level level);

} // Logger
} // System
} // lug
```

You also need to update `src/lug/System/Logger/Logger.cpp` because it also uses this macro to translate each element of the enum into a string.

**Comment by LunaTheFoxgirl** [comment]
Hey, just an update.
I won't be able to do any work on this for 2-3 weeks as i have finals going on right now. I will get back to this as soon as i have hole in my schedule. c:

**Comment by LunaTheFoxgirl** [comment]
I will redo the stuff i've done due to the many changes. Will send an other PR when i've written something that works :P

**Pull request closed without merging**
