### PR TITLE
Improved Logger (Re-PR)

### PR DESCRIPTION
**Pull request by LunaTheFoxgirl**
Added bitflag selected logging modes, removed mode 'off' and fixed compilation.

I'm not sure if the code is bugfree, feel free to test.

### CODE REVIEW

**Comment by LunaTheFoxgirl** [comment]
I don't know how to solve the last test running issues, some help would be nice ^^;

**Comment by saveman71** [comment]
Hi, thanks again for the PR!

For the test issues, the simplest solution is that you manage to test locally, you should see a target generated by CMake to run those tests.

If you can't run the tests locally you can check which tests failed in CircleCI by expanding each failed test at the top of the page [here](https://circleci.com/gh/Lugdunum3D/Lugdunum/1125), and by clicking "more" to expand the remaining tests (*not* "see more tests", but the "more" text).

For the AppVeyor output it's [here](https://ci.appveyor.com/project/Lugdunum/lugdunum/build/1.0.974/job/woa6yl7iq88asj5h/tests)

Since all the failures you encounter are "not called, expected to be called once" errors, I suspect you just forgot to call something somewhere because it seems it is not working at all at the moment. Is the sample outputting the debug output as expected?

Ideally you should add your own tests to validate the feature you're adding too ;)

**Comment by saveman71** [comment]
Also, can you remove the added indentation in Logger.cpp as it will greatlely reduce the diff, and the change is ultimately not going to be part of the merged PR as it is not conformant to the guidelines we mentioned earlier.

**Comment by Quentin01** [comment]
In fact, I think that tests fail because they don't pass the condition based on the level of the message and display nothing.

**Comment by saveman71** [comment]
Note: to build tests locally, you have to set the `BUILD_TESTS` CMake variable to true beforehand, or the targets won't appear.

**Comment by LunaTheFoxgirl** [comment]
The indentation was my coding tool insisting on auto-indenting, i will remove the indentation when i get back to coding on it xD

I've never really worked with this sort of testing technique, so it'll definately be interresting.

**Comment by LunaTheFoxgirl** [comment]
The error message is quite confusing, the problem seems to be starting at `undefined reference to testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'`

**Pull request closed without merging**
